bool request
---
float64 obj_box_dist
float64 obj_grip_dist
float64 obj_rob_dist
float64 obj_x
float64 obj_y
float64 box_x
float64 box_y
float64 grip_x
float64 grip_y
float64 rob_x
float64 rob_y
float64 grip_angle
float64 rob_angle

