Experiment:
    iterations: 16000
    period: 8000
    trials: 10
    worlds:
        - gripper_and_low_friction
        - no_gripper_and_high_friction
Control:
    id: ltm_simulator
    control_prefix: /mdb/control
    info_prefix: /mdb/info
    reward_prefix: /mdb/reward
LTM:
    Files:
        -
            id: goodness
            class: mdb_ltm.file.FileGoodness
            file: goodness.txt
        -
            id: pnodes
            class: mdb_ltm.file.FilePNodes
            file: pnodes.txt
            data: 1000
        -
            id: goals
            class: mdb_ltm.file.FileGoals
            file: goals.txt
            data: 1000
        -
            id: ltm_dump
            class: mdb_ltm.file.FileLTMPeriodicDump
            file: ltm_dump
            data: 1000
    Connectors:
        -
            data: PNode
            ros_name_prefix: /mdb/p_node
            callback: add_node_callback
            default_class: mdb_ltm.pnode.PNode
        -
            data: CNode
        -
            data: Space
            default_class: mdb_ltm.space.NormalCentroidPointBasedSpace
        -
            data: Goal
            ros_name_prefix: /mdb/goal
            callback: add_node_callback
            default_class: mdb_ltm.goal.GoalMotiven
        -
            data: ForwardModel
            ros_name_prefix: /mdb/forward_model
            callback: add_node_callback
        -
            data: Policy
            ros_name_prefix: /mdb/policy
            callback: add_node_callback
    Nodes:
        Perception:
            -
                id: cylinders
                class: mdb_ltm.perception.ObjectListPerception
                data:
                    distance_min: 0.2
                    distance_max: 1.9
                    angle_min: -1.4
                    angle_max: 1.4
                    diameter_min: 0.0
                    diameter_max: 0.15
                ros_name_prefix: /mdb/baxter/sensor/cylinders
            -
                id: boxes
                class: mdb_ltm.perception.ObjectListPerception
                data:
                    distance_min: 0.2
                    distance_max: 1.9
                    angle_min: -1.4
                    angle_max: 1.4
                    diameter_min: 0.0
                    diameter_max: 0.15
                ros_name_prefix: /mdb/baxter/sensor/boxes
            -
                id: ball_in_left_hand
                class: mdb_ltm.perception.Perception
                ros_name_prefix: /mdb/baxter/sensor/ball_in_left_hand
            -
                id: ball_in_right_hand
                class: mdb_ltm.perception.Perception
                ros_name_prefix: /mdb/baxter/sensor/ball_in_right_hand
        Goal:
            -
                id: object_held_with_left_hand
                class: mdb_ltm.goal.GoalObjectHeldLeftHand
                data:
                    space: mdb_ltm.space.PointBasedSpace
                    points:
                        -
                            ball_in_left_hand:
                                data: True
                            ball_in_right_hand:
                                data: False
            -
                id: object_held_with_right_hand
                class: mdb_ltm.goal.GoalObjectHeldRightHand
                data:
                    space: mdb_ltm.space.PointBasedSpace
                    points:
                        -
                            ball_in_left_hand:
                                data: False
                            ball_in_right_hand:
                                data: True
            -
                id: object_held_with_two_hands
                class: mdb_ltm.goal.GoalObjectHeldWithTwoHands
                data:
                    space: mdb_ltm.space.PointBasedSpace
                    points:
                        -
                            ball_in_left_hand:
                                data: True
                            ball_in_right_hand:
                                data: True
            -
                id: frontal_object
                class: mdb_ltm.goal.GoalFrontalObject
                data:
                    space: mdb_ltm.space.PointBasedSpace
                    points:
                        -
                            cylinders:
                                dist: 0.605
                                angle: 0.0
                            ball_in_left_hand:
                                data: False
                            ball_in_right_hand:
                                data: False
            -
                id: object_in_close_box
                class: mdb_ltm.goal.GoalObjectInCloseBox
                data:
                    space: mdb_ltm.space.PointBasedSpace
                    points:
                        -
                            cylinders:
                                dist: 0.575
                                angle: 0.0
                            boxes:
                                dist: 0.575
                                angle: 0.0
                            ball_in_left_hand:
                                data: False
                            ball_in_right_hand:
                                data: False
            -
                id: object_with_robot
                class: mdb_ltm.goal.GoalObjectWithRobot
                data:
                    space: mdb_ltm.space.PointBasedSpace
                    points:
                        -
                            cylinders:
                                dist: 0.45
                                angle: 0.0
                            ball_in_left_hand:
                                data: False
                            ball_in_right_hand:
                                data: False
            -
                id: object_in_far_box
                class: mdb_ltm.goal.GoalObjectInFarBox
                data:
                    space: mdb_ltm.space.PointBasedSpace
                    points:
                        -
                            cylinders:
                                dist: 1.21
                                angle: 0.0
                            boxes:
                                dist: 1.21
                                angle: 0.0
                            ball_in_left_hand:
                                data: False
                            ball_in_right_hand:
                                data: False
            -
                id: approximated_object
                class: mdb_ltm.goal.GoalApproximatedObject
                data:
                    space: mdb_ltm.space.PointBasedSpace
                    points:
                        -
                            cylinders:
                                dist: 0.8
                                angle: 0.0
                            ball_in_left_hand:
                                data: False
                            ball_in_right_hand:
                                data: False
        ForwardModel:
            -
                id: gripper_and_low_friction
                class: mdb_ltm.forward_model.ForwardModel
            -
                id: no_gripper_and_high_friction
                class: mdb_ltm.forward_model.ForwardModel
        Policy:
            -
                id: grasp_object
                class: mdb_ltm.policy.Policy
                ros_name_prefix: /mdb/executed_policy
            -
                id: grasp_with_two_hands
                class: mdb_ltm.policy.Policy
                ros_name_prefix: /mdb/executed_policy
            -
                id: change_hands
                class: mdb_ltm.policy.Policy
                ros_name_prefix: /mdb/executed_policy
            -
                id: sweep_object
                class: mdb_ltm.policy.Policy
                ros_name_prefix: /mdb/executed_policy
            -
                id: put_object_in_box
                class: mdb_ltm.policy.Policy
                ros_name_prefix: /mdb/executed_policy
            -
                id: put_object_with_robot
                class: mdb_ltm.policy.Policy
                ros_name_prefix: /mdb/executed_policy
            -
                id: throw
                class: mdb_ltm.policy.Policy
                ros_name_prefix: /mdb/executed_policy
            -
                id: ask_nicely
                class: mdb_ltm.policy.Policy
                ros_name_prefix: /mdb/executed_policy
SimulatedBaxter:
    Perceptions:
        -
            id: cylinders
            ros_name_prefix: /mdb/baxter/sensor/cylinders
        -
            id: boxes
            ros_name_prefix: /mdb/baxter/sensor/boxes
        -
            id: ball_in_left_hand
            ros_name_prefix: /mdb/baxter/sensor/ball_in_left_hand
        -
            id: ball_in_right_hand
            ros_name_prefix: /mdb/baxter/sensor/ball_in_right_hand
        -
            id: clean_area
            ros_name_prefix: /mdb/baxter/sensor/happy_human
Baxter:
    Sensors:
        -
            id: camera
            ros_name_prefix: /mdb/baxter/camera
    Perceptions:
        -
            id: cylinders
            ros_name_prefix: /mdb/baxter/sensor/cylinders
        -
            id: boxes
            ros_name_prefix: /mdb/baxter/sensor/boxes
        -
            id: ball_in_left_hand
            ros_name_prefix: /mdb/baxter/sensor/ball_in_left_hand
        -
            id: ball_in_right_hand
            ros_name_prefix: /mdb/baxter/sensor/ball_in_right_hand
        -
            id: clean_area
            ros_name_prefix: /mdb/baxter/sensor/happy_human
        -
            id: monitor_image
            ros_name_prefix: /mdb/baxter/sensor/monitor_image
