Experiment:
    iterations: 10000
    period: 10001
    trials: 10001
    worlds: ['gripper_and_low_friction_two_boxes']
Control:
    id: ltm_simulator
    ros_name_prefix: /mdb/control
    executed_policy_prefix: /mdb/executed_policy
LTM:
    Files:
        -
            id: goodness
            class: mdb_ltm.file.FileGoodness
            file: goodness.txt
        -
            id: pnodes
            class: mdb_ltm.file.FilePNodes
            file: pnodes.txt
            data: 1000
        -
            id: ltm_dump
            class: mdb_ltm.file.FileLTMPeriodicDump
            file: ltm_dump
            data: 1000
    Connectors:
        -
            data: PNode
            ros_name_prefix: /mdb/p_node
            callback: add_node_callback
            default_class: mdb_ltm.pnode.PNodeActCentroidAndNormal
        -
            data: CNode
            ros_name_prefix: /mdb/c_node
            callback: add_node_callback
        -
            data: Goal
            ros_name_prefix: /mdb/goal
            callback: add_node_callback
            default_class: mdb_ltm.goal.GoalMotiven
        -
            data: ForwardModel
            ros_name_prefix: /mdb/forward_model
            callback: add_node_callback
        -
            data: Policy
            ros_name_prefix: /mdb/policy
            callback: add_node_callback
    Nodes:
        Perception:
            -
                id: cylinders
                class: mdb_ltm.perception.ObjectListPerception
                data:
                    distance_min: 0.2
                    distance_max: 1.9
                    angle_min: -1.4
                    angle_max: 1.4
                    diameter_min: 0.0
                    diameter_max: 0.15
                ros_name_prefix: /mdb/baxter/sensor/cylinders
            -
                id: boxes
                class: mdb_ltm.perception.ObjectListPerception
                data:
                    distance_min: 0.2
                    distance_max: 1.9
                    angle_min: -1.4
                    angle_max: 1.4
                    diameter_min: 0.0
                    diameter_max: 0.15
                ros_name_prefix: /mdb/baxter/sensor/boxes
            -
                id: ball_in_left_hand
                class: mdb_ltm.perception.Perception
                ros_name_prefix: /mdb/baxter/sensor/ball_in_left_hand
            -
                id: ball_in_right_hand
                class: mdb_ltm.perception.Perception
                ros_name_prefix: /mdb/baxter/sensor/ball_in_right_hand
        ForwardModel:
            -
                id: gripper_and_low_friction
                class: mdb_ltm.forward_model.ForwardModelGripper
        Policy:
            -
                id: grasp_object
                class: mdb_ltm.policy.Policy
                ros_name_prefix: /mdb/executed_policy
            -
                id: grasp_with_two_hands
                class: mdb_ltm.policy.Policy
                ros_name_prefix: /mdb/executed_policy
            -
                id: change_hands
                class: mdb_ltm.policy.Policy
                ros_name_prefix: /mdb/executed_policy
            -
                id: sweep_object
                class: mdb_ltm.policy.Policy
                ros_name_prefix: /mdb/executed_policy
            -
                id: put_object_in_box
                class: mdb_ltm.policy.Policy
                ros_name_prefix: /mdb/executed_policy
            -
                id: put_object_with_robot
                class: mdb_ltm.policy.Policy
                ros_name_prefix: /mdb/executed_policy
            -
                id: throw
                class: mdb_ltm.policy.Policy
                ros_name_prefix: /mdb/executed_policy
            -
                id: ask_nicely
                class: mdb_ltm.policy.Policy
                ros_name_prefix: /mdb/executed_policy
Simulator:
    Sensors:
        -
            id: cylinders
            ros_name_prefix: /mdb/baxter/sensor/cylinders
        -
            id: boxes
            ros_name_prefix: /mdb/baxter/sensor/boxes
        -
            id: ball_in_left_hand
            ros_name_prefix: /mdb/baxter/sensor/ball_in_left_hand
        -
            id: ball_in_right_hand
            ros_name_prefix: /mdb/baxter/sensor/ball_in_right_hand
        -
            id: clean_area
            ros_name_prefix: /mdb/baxter/sensor/happy_human
