# Topic to publish reward
/mdb/reward_topic: /mdb/reward
/mdb/reward_msg: std_msgs.msg.Float64
# Topic to communicate with the simulator
/mdb/control_topic: /mdb/baxter/control
/mdb/control_msg: mdb_common.msg.ControlMsg
# Topic for publishing P-node creation
/mdb/p_node_topic: /mdb/ltm/p_node
/mdb/p_node_msg: mdb_common.msg.PNodeMsg
# Topic for publishing Goal creation
/mdb/goal_topic: /mdb/motiven/goal
/mdb/goal_msg: mdb_common.msg.GoalMsg
# Topic for publishing goal activations
/mdb/goal_activation_topic: /mdb/motiven/goal_activation
/mdb/goal_activation_msg: mdb_common.msg.GoalActivationMsg
# Topic for publishing goal accomplishment
/mdb/goal_ok_topic: /mdb/motiven/goal_ok
/mdb/goal_ok_msg: mdb_common.msg.GoalOkMsg
# Topic for publishing Forward Model creation
/mdb/forward_model_topic: /mdb/stm/forward_model
/mdb/forward_model_msg: mdb_common.msg.ForwardModelMsg
# Topic for publishing Policy creation
/mdb/policy_topic: /mdb/stm/policy
/mdb/policy_msg: mdb_common.msg.PolicyMsg
# Topic for publishing the executed policy's id
/mdb/executed_policy_topic: /mdb/ltm/executed_policy
/mdb/executed_policy_msg: std_msgs.msg.String
# Topics for Baxter's sensors
/mdb/baxter/sensor/cylinders_topic: /mdb/baxter/sensor/cylinders
/mdb/baxter/sensor/cylinders_msg: mdb_common.msg.ObjectListMsg
/mdb/baxter/sensor/boxes_topic: /mdb/baxter/sensor/boxes
/mdb/baxter/sensor/boxes_msg: mdb_common.msg.ObjectListMsg
/mdb/baxter/sensor/ball_in_left_hand_topic: /mdb/baxter/sensor/ball_in_left_hand
/mdb/baxter/sensor/ball_in_left_hand_msg: std_msgs.msg.Bool
/mdb/baxter/sensor/ball_in_right_hand_topic: /mdb/baxter/sensor/ball_in_right_hand
/mdb/baxter/sensor/ball_in_right_hand_msg: std_msgs.msg.Bool
/mdb/baxter/sensor/happy_human_topic: /mdb/baxter/sensor/happy_human
/mdb/baxter/sensor/happy_human_msg: std_msgs.msg.Bool
/mdb/baxter/sensor/monitor_image_topic: /mdb/baxter/sensor/monitor_image
/mdb/baxter/sensor/monitor_image_msg: sensor_msgs.msg.Image
# Topic for publishing commands to baxter_throwing policy
/mdb/superthrow_topic: /baxter_throwing/command
/mdb/superthrow_msg: std_msgs.msg.Int16
# Topic for communication with the X-tion camera
/mdb/baxter/camera_topic: /camera/rgb/image_rect_color
/mdb/baxter/camera_msg: sensor_msgs.msg.Image
