#!/usr/bin/env python
"""
MDB.

https://github.com/GII/MDB
"""

import os
import sys


def execute(answer, command):
    """Launches something in a terminal."""
    if answer.lower() in "yes":
        os.system(command)
        input("Launching... Press Enter to continue when it finishes starting...")


def main():
    """Launches everything needed to run the MDB."""
    if "linux" in sys.platform:
        terminal = "gnome-terminal -- "
    elif sys.platform == "darwin":
        terminal = "open -a Terminal -n --args "
    else:
        sys.exit("Error: O.S. doesn't suported by this sript!")
    # Begin needed ROS stuff
    roscore = terminal + "roscore"
    baxter_gazebo = terminal + "roslaunch baxter_gazebo baxter_world.launch"
    baxter_action_server = terminal + "rosrun baxter_interface joint_trajectory_action_server.py"
    baxter_moveit = terminal + "roslaunch baxter_moveit_config baxter_grippers.launch"
    mdb = terminal + "roslaunch mdb_common mdb.launch"
    # End needed ROS stuff
    execute(input("Do you want to launch roscore? (y/N): "), roscore)
    execute(input("Do you want to launch the Gazebo simulator? (y/N): "), baxter_gazebo)
    execute(input("Do you want to launch the Baxter joint trajectory action server? (y/N): "), baxter_action_server)
    execute(input("Do you want to launch MoveIt interface? (y/N): "), baxter_moveit)
    execute(input("Do you want to launch MDB? (y/N): "), mdb)


if __name__ == "__main__":
    main()
