#!/usr/bin/env python
"""
MDB.

https://github.com/GII/MDB
"""

# Python 2 compatibility imports
from __future__ import absolute_import, division, print_function, unicode_literals
from future import standard_library

standard_library.install_aliases()
from builtins import *  # noqa pylint: disable=unused-wildcard-import,wildcard-import

# Library imports
import rospy
from baxter_core_msgs.msg import HeadState

# MDB imports
from mdb_robots_policies.srv import GetHeadState


class get_head_state(object):
    def __init__(self):
        rospy.init_node("get_head_state_server")

        self.current_state = None

        self.head_state_sb = rospy.Subscriber("/robot/head/head_state", HeadState, self.head_state_cb)
        self.geths_sv = rospy.Service("/get_head_state", GetHeadState, self.handle_geths)

    def head_state_cb(self, state):
        self.current_state = state

    def handle_geths(self, req):
        if req.request.data:
            print("Sending current joint states")
            # while len(self.current_state.position)==1:
            # pass
            return self.current_state
        else:
            return None


def get_head_state_server():
    get_head_state()
    rospy.spin()


if __name__ == "__main__":
    get_head_state_server()
