#!/usr/bin/env python
"""
MDB.

https://github.com/GII/MDB
"""

# Python 2 compatibility imports
from __future__ import absolute_import, division, print_function
from future import standard_library

standard_library.install_aliases()
from builtins import *  # noqa pylint: disable=unused-wildcard-import,wildcard-import

# Library imports
import rospy
from sensor_msgs.msg import JointState

# MDB imports
from mdb_robots_policies.srv import GetJointsState


class get_joints_state(object):
    def __init__(self):
        rospy.init_node("get_joints_state_server")

        self.current_state = None

        self.joint_states_sub = rospy.Subscriber("/robot/joint_states", JointState, self.joint_states_cb)
        self.getjs_srv = rospy.Service("get_joints_state", GetJointsState, self.handle_getjs)

    def joint_states_cb(self, state):
        self.current_state = state

    def handle_getjs(self, req):
        if req.request.data:
            print("Sending current joint states")
            while len(self.current_state.position) == 1:
                pass
            return self.current_state
        else:
            return None


def get_joints_state_server():
    get_joints_state()
    rospy.spin()


if __name__ == "__main__":
    get_joints_state_server()
