#!/usr/bin/env python
"""
MDB.

Available from https://github.com/robotsthatdream/MDB
Distributed under GPLv3.
"""

import argparse
from mdb_robots.robobo import Robobo


def start_robobo():
    """Create the node in charge of providing Robobo sensorization to MDB."""
    parser = argparse.ArgumentParser(description="This script starts the Robobo sensorization component of the MDB.")
    parser.add_argument("-c", "--config_file", help="Configuration file in yaml format")
    parser.add_argument("-l", "--log_level", help="ROS log level (DEBUG, INFO, WARN, ERROR or FATAL)")
    args, _ = parser.parse_known_args()
    kwargs = vars(args)
    robobo = Robobo()
    robobo.run(**kwargs)


if __name__ == "__main__":
    start_robobo()
