#!/usr/bin/env python
"""
MDB

Available from https://github.com/robotsthatdream/MDB
Distributed under GPLv3.
"""

# Python 2 compatibility imports
from __future__ import absolute_import, division, print_function, unicode_literals
from future import standard_library

standard_library.install_aliases()
from builtins import *  # noqa pylint: disable=unused-wildcard-import,wildcard-import

# Library imports
import argparse

# MDB imports
from mdb_view.view import View


def setup_node():
    """Setup and run the VIEW object"""
    parser = argparse.ArgumentParser(description="This script starts the VIEW component of the MDB 3.0")
    parser.add_argument("-s", "--seed", help="Yaml file with some nodes to populate the LTM")
    parser.add_argument("-l", "--log_level", help="ROS log level (DEBUG, INFO, WARN, ERROR or FATAL)")
    parser.add_argument("-d", "--save_dir", help="Directory to save images and files")
    args, _ = parser.parse_known_args()
    kwargs = vars(args)
    view = View()
    view.run(**kwargs)


if __name__ == "__main__":
    setup_node()
