#!/usr/bin/env python
"""
The shiny, all new, MDB 3.

Available from https://github.com/robotsthatdream/MDB
Distributed under GPLv3.
"""

import argparse
from mdb_motiven.motiven import MOTIVEN


def start_motiven():
    """Create a MOTIVEN object and run it."""
    parser = argparse.ArgumentParser(description="This script starts the MOTIVEN component of the MDB 3.0")
    parser.add_argument(
        "-b",
        "--backup",
        help="MOTIVEN backup / memory dump file. "
        "If it exists, it reads its contents. "
        "Otherwise, it creates the file. "
        "When the process ends, the backup file is updated.",
    )
    parser.add_argument("-l", "--log_level", help="ROS log level (DEBUG, INFO, WARN, ERROR or FATAL)")
    parser.add_argument("-s", "--standalone", action="store_true", help="Run MOTIVEN without other MDB components")
    parser.add_argument("-p", "--plot", action="store_true", help="Show MOTIVEN diagrams in real time.")
    args, _ = parser.parse_known_args()
    kwargs = vars(args)
    backup = kwargs.pop("backup", None)
    motiven = MOTIVEN.restore(backup)
    motiven.run(**kwargs)


if __name__ == "__main__":
    start_motiven()
