#!/usr/bin/env python
"""
The shiny, all new, MDB 3.

Available from https://github.com/robotsthatdream/MDB
Distributed under GPLv3.
"""

import argparse
from mdb_motiven.motiven import MOTIVEN


def start_motiven():
    """Create a MOTIVEN object and run it."""
    parser = argparse.ArgumentParser(description='This script starts the MOTIVEN component of the MDB 3.0')
    parser.add_argument('-l', '--log_level', help='ROS log level (DEBUG, INFO, WARN, ERROR or FATAL)')
    parser.add_argument('-s', '--standalone', action='store_true', help='Run MOTIVEN without other MDB components')
    args, _ = parser.parse_known_args()
    kwargs = vars(args)
    instance = MOTIVEN()
    instance.run(**kwargs)


if __name__ == '__main__':
    start_motiven()
