#!/usr/bin/env python
"""
MDB.

Available from https://github.com/robotsthatdream/MDB
Distributed under GPLv3.
"""

import sys
from skimage import io
from mdb_robots.baxter import Baxter


if __name__ == "__main__":
    image = Baxter(objects_database=sys.argv[2]).classify_objects(io.imread(sys.argv[1]))
    io.imshow(image)
    io.show()
