#!/usr/bin/env python
"""
MDB.

Available from https://github.com/robotsthatdream/MDB
Distributed under GPLv3.
"""

import argparse
from mdb_simulator.simulator import LTMSim


def start_ltm_simulator():
    """Create a LTM simulator object and run it."""
    parser = argparse.ArgumentParser(
        description="This script starts a very simple simulator to run LTM experiments"
    )
    parser.add_argument(
        "-rs", "--random_seed", type=int, help="Set the seed of the random number generator"
    )
    parser.add_argument("-c", "--config_file", help="Configuration file in yaml format")
    parser.add_argument(
        "-l", "--log_level", help="ROS log level (DEBUG, INFO, WARN, ERROR or FATAL)"
    )
    args, _ = parser.parse_known_args()
    kwargs = vars(args)
    ltm = LTMSim()
    ltm.run(**kwargs)


if __name__ == "__main__":
    start_ltm_simulator()
