#!/usr/bin/env python
"""
MDB.

https://github.com/GII/MDB
"""

import argparse
import pandas
import matplotlib.pyplot as plt
import seaborn


def pnodes_grouped_success_average():
    """Merge P-Node success files."""
    parser = argparse.ArgumentParser(description="Merge P-Node success files")
    parser.add_argument("files", nargs="+", help="File names to merge")
    args = parser.parse_args()
    data = []
    for file_name in args.files:
        data.append(
            pandas.read_csv(
                file_name,
                sep="\t",
                names=("Iteration", "P-node", "Successes", "Activations", "% success"),
                index_col=(0, 1),
            )
        )
    data = pandas.concat(data)
    seaborn.set_theme(context="paper", style="whitegrid")
    seaborn.relplot(
        data=data, x="Iteration", y="% success", hue="P-node", col="P-node", col_wrap=4, kind="line"
    ).set_axis_labels("Iteration", "% rewarded iterations")
    plt.show()


if __name__ == "__main__":
    pnodes_grouped_success_average()
