#!/usr/bin/env python
"""
MDB.

https://github.com/GII/MDB
"""

import argparse
import bz2
import sys
import pandas
import magic
import matplotlib.pyplot as plt
import seaborn


def open_file(name):
    """Open a file using its magic number to identify its contents."""
    file_type = magic.from_file(name)
    if "text" in file_type:
        return open(name, encoding="utf-8")
    if "bzip2" in file_type:
        return bz2.open(name)
    print("Unsupported file!!!")
    sys.exit(1)


def pnodes_grouped_success_average():
    """Merge P-Node success files."""
    parser = argparse.ArgumentParser(description="Merge P-Node success files")
    parser.add_argument("files", nargs="+", help="File names to merge")
    args = parser.parse_args()
    data = []
    for name in args.files:
        table = pandas.read_csv(
            open_file(name),
            sep="\t",
            names=("Iteration", "P-node", "Successes", "Activations", "% success"),
            index_col=(0, 1),
        )
        if "puntos" in name:
            space_type = "Baseline"
        elif "svm" in name:
            space_type = "SVM"
        elif "ann" in name:
            space_type = "ANN"
        table["Type"] = space_type
        data.append(table)
    data = pandas.concat(data)
    seaborn.set_theme(context="paper", style="whitegrid")
    seaborn.relplot(
        data=data, x="Iteration", y="% success", hue="Type", col="P-node", col_wrap=4, kind="line"
    ).set_axis_labels("Iteration", "% rewarded iterations")
    plt.show()


if __name__ == "__main__":
    pnodes_grouped_success_average()
