#!/usr/bin/env python
"""
MDB.

https://github.com/GII/MDB
"""

import argparse


def split_pnodes():
    """Split P-Node data from a log into several files, one per P-Node."""
    parser = argparse.ArgumentParser(
        description="This script splits P-Node data from a log file into several small files, one per P-Node"
    )
    parser.add_argument(
        "-f",
        "--file",
        help="File with the points of every P-Node for every iteration of an experiment",
    )
    args, _ = parser.parse_known_args()
    kwargs = vars(args)
    file_name = kwargs["file"]
    if file_name is None:
        parser.print_help()
    else:
        data_file = open(file_name, "r")
        data_file.readline()
        pnode_files = {}
        for line in data_file:
            _, pnode_id, _, _, _, _, _, _, _, _, _ = line.split()
            if pnode_id not in pnode_files:
                pnode_files[pnode_id] = open(file_name + "_" + pnode_id, "w")
            pnode_files[pnode_id].write(line)


if __name__ == "__main__":
    split_pnodes()
